// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserManagement.Infrastructure.AppDbContexts;

#nullable disable

namespace UserManagement.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250530064825_AddCreatedDateColumnAndAddInitData")]
    partial class AddCreatedDateColumnAndAddInitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01971fe9-5030-7517-b000-a5a7b1368270"),
                            CreatedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@example.com",
                            JoinDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("01971fe9-fb80-7a02-84c7-8e6f604b3f86"),
                            CreatedDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user2@example.com",
                            JoinDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Username = "user2"
                        },
                        new
                        {
                            Id = new Guid("01971fea-1cb7-7d2f-b391-4107b22812a8"),
                            CreatedDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user3@example.com",
                            JoinDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Username = "user3"
                        },
                        new
                        {
                            Id = new Guid("01971fea-37cc-7bcc-8071-ecad077d0a53"),
                            CreatedDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user4@example.com",
                            JoinDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Username = "user4"
                        },
                        new
                        {
                            Id = new Guid("01971fea-555d-7c5e-ac91-8138324bb6a0"),
                            CreatedDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user5@example.com",
                            JoinDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Username = "user5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
